// Contenido editable del catálogo y del blog. Pide a Codex que modifique este archivo
// cuando necesites añadir productos, cambiar stock o publicar artículos.
(function () {
'use strict';
var productos = [
  {
    slug: "m1",
    nombre: "Codificadora M1",
    modelo: "M1",
    tipo: "Codificadora",
    familia: "Portátil",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Compacta, táctil y diseñada para codificar productos secos y congelados.",
    descripcion: "Codificadora portátil de una mano con pantalla táctil de 3,5 pulgadas. Permite imprimir fechas, lotes, textos, logotipos y códigos sobre superficies planas, curvas, rugosas y espacios reducidos.",
    imagen: "/assets/productos/m1/principal.webp",
    galeria: Array.from({ length: 7 }, (_, i) => `/assets/productos/m1/galeria-${i + 1}.webp`),
    ficha: "/assets/productos/m1/ficha-tecnica.pdf",
    video: "https://www.youtube-nocookie.com/embed/P94ap01WZgY",
    altura: "12,7 mm",
    alturaFiltro: "12,7 mm",
    destacados: ["Pantalla táctil de 3,5 pulgadas", "Hasta 1,5 m de longitud", "Peso ligero de 218 g", "Resolución de hasta 1000 DPI"],
    incluye: ["Tinta solvente", "Manual de usuario", "Cable USB tipo C", "Pendrive"],
    especificaciones: [
      ["Pantalla", "Táctil de 3,5 pulgadas"],
      ["Líneas de impresión", "1 a 4 líneas"],
      ["Altura de impresión", "12,7 mm"],
      ["Longitud de impresión", "1,5 m"],
      ["Precisión", "1000 DPI / 600 DPI"],
      ["Formatos de imagen", "JPG, BMP y PNG"],
      ["Superficies", "Cartón, tubo, cable, metal, plástico, aluminio, papel y más"],
      ["Batería", "4 a 6 horas"],
      ["Peso", "218 g"],
      ["Dimensiones", "85 × 106 mm"],
      ["Capacidad de tinta", "42 ml"],
      ["Alimentación", "110 V - 220 V / carga tipo C"],
    ],
    compatibles: ["S70", "SK10"],
  },
  {
    slug: "b15",
    nombre: "Codificadora B15",
    modelo: "B15",
    tipo: "Codificadora",
    familia: "Portátil Wi-Fi",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Codificación inalámbrica para productos secos, húmedos y congelados.",
    descripcion: "Equipo portátil controlado mediante aplicación para Android o iOS. Su conexión Wi-Fi y tinta solvente permiten una operación sencilla y flexible en distintas líneas de trabajo.",
    imagen: "/assets/productos/b15/principal.webp",
    galeria: Array.from({ length: 8 }, (_, i) => `/assets/productos/b15/galeria-${i + 1}.webp`),
    ficha: "/assets/productos/b15/ficha-tecnica.pdf",
    video: "https://www.youtube-nocookie.com/embed/EAKc1gC-TPA",
    altura: "12,7 mm",
    alturaFiltro: "12,7 mm",
    destacados: ["Conexión Wi-Fi", "Aplicación Android e iOS", "Hasta 6 líneas", "Tinta solvente de secado rápido"],
    incluye: ["Tinta solvente", "Manual de usuario", "Cable USB tipo C", "Pendrive"],
    especificaciones: [
      ["Conectividad", "Wi-Fi"],
      ["Interfaz", "Aplicación para Android e iOS"],
      ["Líneas de impresión", "1 a 6 líneas"],
      ["Altura de impresión", "12,7 mm"],
      ["Longitud de impresión", "1 m"],
      ["Resolución", "300 DPI"],
      ["Velocidad", "30 m/min"],
      ["Formatos de imagen", "JPG, BMP y PNG"],
      ["Batería", "4 a 6 horas"],
      ["Peso", "195 g"],
      ["Capacidad de tinta", "42 ml"],
      ["Temperatura de trabajo", "5 °C a 35 °C"],
    ],
    compatibles: ["BB22B"],
  },
  {
    slug: "bt6205bl",
    nombre: "Codificadora BT6205BL",
    modelo: "BT6205BL",
    tipo: "Codificadora",
    familia: "Manual y automática",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Equipo tipo pistola para impresión manual o integrada a una banda transportadora.",
    descripcion: "Codificadora ligera con pantalla de alta definición y puerto para fotosensor. Se adapta a trabajos manuales y a procesos automáticos de producción.",
    imagen: "/assets/productos/bt6205bl/principal.webp",
    galeria: Array.from({ length: 8 }, (_, i) => `/assets/productos/bt6205bl/galeria-${i + 1}.webp`),
    ficha: "/assets/productos/bt6205bl/ficha-tecnica.pdf",
    video: "https://www.youtube-nocookie.com/embed/hQ1XnHxlezo",
    altura: "12,7 mm",
    alturaFiltro: "12,7 mm",
    destacados: ["Uso manual o automático", "Batería de hasta 16 horas", "Pantalla HD de 4,3 pulgadas", "Puerto para fotosensor"],
    incluye: ["Tinta", "Lápiz óptico", "Pendrive", "Manual", "Regla de precisión", "Adaptador", "Cargador", "Sensor"],
    especificaciones: [
      ["Sistema operativo", "Linux"],
      ["Líneas de impresión", "1 a 6 líneas"],
      ["Altura de impresión", "12,7 mm"],
      ["Longitud de impresión", "1 m"],
      ["Pantalla", "4,3 pulgadas de alta definición"],
      ["Resolución", "600 / 300 DPI"],
      ["Velocidad", "30 m/min"],
      ["Memoria", "128 MB"],
      ["Batería", "Hasta 16 horas"],
      ["Peso", "420 g"],
      ["Dimensiones", "208 × 113 × 45 mm"],
      ["Distancia de impresión", "2 a 5 mm"],
    ],
    compatibles: ["BB22B"],
  },
  {
    slug: "bt6210bl",
    nombre: "Codificadora BT6210BL",
    modelo: "BT6210BL",
    tipo: "Codificadora",
    familia: "Manual y automática",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Mayor altura de impresión para producciones que requieren más información por pasada.",
    descripcion: "Codificadora tipo pistola con altura de 25,4 mm, pantalla de alta definición y conexión para fotosensor. Puede trabajar de forma manual o acoplada a una banda transportadora.",
    imagen: "/assets/productos/bt6210bl/principal.webp",
    galeria: [
      "/assets/productos/bt6210bl/galeria-1.webp", "/assets/productos/bt6210bl/galeria-2.webp", "/assets/productos/bt6210bl/galeria-3.png", "/assets/productos/bt6210bl/galeria-4.webp", "/assets/productos/bt6210bl/galeria-5.webp", "/assets/productos/bt6210bl/galeria-6.webp", "/assets/productos/bt6210bl/galeria-7.webp", "/assets/productos/bt6210bl/galeria-8.webp",
    ],
    ficha: "/assets/productos/bt6210bl/ficha-tecnica.pdf",
    video: "https://www.youtube-nocookie.com/embed/kITvkkMcnz4",
    altura: "25,4 mm",
    alturaFiltro: "25,4 mm",
    destacados: ["Hasta 10 líneas", "Longitud de hasta 2 m", "Batería de 16 horas", "Trabajo manual y automático"],
    incluye: ["Tinta", "Lápiz óptico", "Pendrive", "Manual", "Regla de precisión", "Adaptador", "Cargador", "Sensor"],
    especificaciones: [
      ["Sistema operativo", "Linux"],
      ["Líneas de impresión", "1 a 10 líneas"],
      ["Altura de impresión", "25,4 mm"],
      ["Longitud de impresión", "2 m"],
      ["Pantalla", "4,3 pulgadas de alta definición"],
      ["Resolución", "300 DPI"],
      ["Velocidad", "15 m/min"],
      ["Memoria", "128 MB"],
      ["Batería", "Hasta 16 horas"],
      ["Peso", "430 g"],
      ["Dimensiones", "208 × 133 × 45 mm"],
      ["Distancia de impresión", "2 a 5 mm"],
    ],
    compatibles: ["EB21B", "EB22BL"],
  },
  {
    slug: "b45",
    nombre: "Codificadora B45",
    modelo: "B45",
    tipo: "Codificadora",
    familia: "Industrial",
    disponibilidad: "bajo-pedido",
    disponibilidadTexto: "Disponible bajo pedido",
    resumen: "Codificadora industrial de gran formato para textos, logotipos y señalética.",
    descripcion: "Solución manual o automática con dos tintas y una altura de impresión de hasta 50 mm. Indicada para operaciones de mayor volumen y personalización industrial.",
    imagen: "/assets/productos/b45/principal.webp",
    galeria: Array.from({ length: 8 }, (_, i) => `/assets/productos/b45/galeria-${i + 1}.webp`),
    ficha: "/assets/productos/b45/ficha-tecnica.pdf",
    altura: "50 mm",
    alturaFiltro: "50 mm",
    destacados: ["Hasta 20 líneas", "Altura de impresión de 50 mm", "Dos tintas", "Uso manual o automático"],
    incluye: ["Dos tintas", "Inyector y adaptador", "Lápiz óptico", "Pendrive", "Manual", "Regla", "Cargador"],
    especificaciones: [
      ["Sistema operativo", "Linux"],
      ["Líneas de impresión", "1 a 20 líneas"],
      ["Altura de impresión", "50 mm"],
      ["Longitud de impresión", "2 m"],
      ["Pantalla", "5 pulgadas de alta definición"],
      ["Resolución", "300 DPI"],
      ["Velocidad", "15 m/min"],
      ["Memoria", "4 GB"],
      ["Batería", "Hasta 8 horas"],
      ["Peso", "860 g"],
      ["Dimensiones", "220 × 110 × 75 mm"],
      ["Distancia de impresión", "2 a 5 mm"],
    ],
    compatibles: ["EB21B", "EB22BL"],
  },
  {
    slug: "b85",
    nombre: "Codificadora B85",
    modelo: "B85",
    tipo: "Codificadora",
    familia: "Industrial gran formato",
    disponibilidad: "bajo-pedido",
    disponibilidadTexto: "Disponible bajo pedido",
    resumen: "La mayor altura de la línea Rigel para codificación y personalización industrial.",
    descripcion: "Equipo de cuatro tintas capaz de imprimir hasta 40 líneas y cubrir formatos de gran altura. Se adapta a procesos manuales y automáticos.",
    imagen: "/assets/productos/b85/principal.webp",
    galeria: Array.from({ length: 7 }, (_, i) => `/assets/productos/b85/galeria-${i + 1}.webp`),
    ficha: "/assets/productos/b85/ficha-tecnica.pdf",
    altura: "100 mm",
    alturaFiltro: "100 mm",
    destacados: ["Hasta 40 líneas", "Altura de impresión de 100 mm", "Cuatro tintas", "Resolución 600 / 300 DPI"],
    incluye: ["Cuatro tintas", "Accesorios de precisión", "Pendrive", "Manual", "Adaptador", "Cargador"],
    especificaciones: [
      ["Sistema operativo", "Linux"],
      ["Líneas de impresión", "1 a 40 líneas"],
      ["Altura de impresión", "100 mm"],
      ["Longitud de impresión", "2 m"],
      ["Pantalla", "4,3 pulgadas de alta definición"],
      ["Resolución", "600 / 300 DPI"],
      ["Velocidad", "30 m/min"],
      ["Nivel de gris", "1 a 5"],
      ["Temperatura de trabajo", "5 °C a 35 °C"],
      ["Modos de uso", "Manual y automático"],
      ["Distancia de impresión", "2 a 5 mm"],
      ["Superficies", "Plástico, vidrio, metal, aluminio, cartón, algodón y más"],
    ],
    compatibles: ["EB21B", "EB22BL"],
  },
  {
    slug: "bb22b",
    nombre: "Tinta BENTSAI BB22B",
    modelo: "BB22B",
    tipo: "Tinta",
    familia: "Tinta solvente",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Tinta solvente de secado rápido para impresiones de 12,7 mm.",
    descripcion: "Consumible original BENTSAI para mantener una impresión nítida, estable y de rápida adherencia sobre distintas superficies.",
    imagen: "/assets/productos/bb22b/principal.webp",
    galeria: [],
    altura: "12,7 mm",
    alturaFiltro: "12,7 mm",
    destacados: ["Tinta solvente", "Secado rápido", "Impresión de 12,7 mm", "Tinta original"],
    especificaciones: [["Tecnología", "Inyección térmica TIJ"], ["Altura", "12,7 mm / 0,5 pulg"], ["Tipo de tinta", "Solvente de secado rápido"], ["Compatibilidad", "B15 y BT6205BL"]],
    compatibles: ["B15", "BT6205BL"],
  },
  {
    slug: "eb21b",
    nombre: "Tinta BENTSAI EB21B",
    modelo: "EB21B",
    tipo: "Tinta",
    familia: "Tinta solvente",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Tinta solvente para equipos de mayor altura y aplicaciones industriales.",
    descripcion: "Tinta original BENTSAI de secado rápido para impresiones consistentes sobre plástico, vidrio, metal, cartón y otros materiales.",
    imagen: "/assets/productos/eb21b/principal.webp",
    galeria: [],
    altura: "25,4 mm",
    alturaFiltro: "25,4 mm",
    destacados: ["Tinta solvente", "Secado rápido", "Uso industrial", "Tinta original"],
    especificaciones: [["Tecnología", "Inyección térmica TIJ"], ["Altura", "25,4 mm / 1 pulg"], ["Tipo de tinta", "Solvente de secado rápido"], ["Compatibilidad", "BT6210BL, B45 y B85"]],
    compatibles: ["BT6210BL", "B45", "B85"],
  },
  {
    slug: "eb22bl",
    nombre: "Tinta BENTSAI EB22BL",
    modelo: "EB22BL",
    tipo: "Tinta",
    familia: "Tinta solvente",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Consumible original de larga duración para codificación industrial.",
    descripcion: "Tinta BENTSAI para líneas de impresión de mayor altura, con tinta solvente de rápida adherencia y acabado definido.",
    imagen: "/assets/productos/eb22bl/principal.webp",
    galeria: [],
    altura: "25,4 mm",
    alturaFiltro: "25,4 mm",
    destacados: ["Tinta solvente", "Larga duración", "Uso industrial", "Tinta original"],
    especificaciones: [["Tecnología", "Inyección térmica TIJ"], ["Altura", "25,4 mm / 1 pulg"], ["Tipo de tinta", "Solvente de secado rápido"], ["Compatibilidad", "BT6210BL, B45 y B85"]],
    compatibles: ["BT6210BL", "B45", "B85"],
  },
  {
    slug: "s70",
    nombre: "Tinta S70",
    modelo: "S70",
    tipo: "Tinta",
    familia: "Tinta solvente",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Tinta solvente de 12,7 mm compatible con la codificadora M1.",
    descripcion: "Consumible para impresión de fechas, lotes, textos, logotipos y códigos sobre diversas superficies.",
    imagen: "/assets/productos/s70/principal.webp",
    galeria: [],
    altura: "12,7 mm",
    alturaFiltro: "12,7 mm",
    destacados: ["Tinta solvente", "Secado rápido", "12,7 mm", "Compatible con M1"],
    especificaciones: [["Tecnología", "Inyección térmica TIJ"], ["Altura", "12,7 mm / 0,5 pulg"], ["Tipo de tinta", "Solvente de secado rápido"], ["Compatibilidad", "M1"]],
    compatibles: ["M1"],
  },
  {
    slug: "sk10",
    nombre: "Tinta SK10",
    modelo: "SK10",
    tipo: "Tinta",
    familia: "Tinta solvente",
    disponibilidad: "disponible",
    disponibilidadTexto: "Disponible",
    resumen: "Tinta de 12,7 mm para codificación portátil con el equipo M1.",
    descripcion: "Tinta solvente de secado rápido para resultados nítidos en papel, plástico, cartón, metal y otras superficies.",
    imagen: "/assets/productos/sk10/principal.webp",
    galeria: [],
    altura: "12,7 mm",
    alturaFiltro: "12,7 mm",
    destacados: ["Tinta solvente", "Secado rápido", "12,7 mm", "Compatible con M1"],
    especificaciones: [["Tecnología", "Inyección térmica TIJ"], ["Altura", "12,7 mm / 0,5 pulg"], ["Tipo de tinta", "Solvente de secado rápido"], ["Compatibilidad", "M1"]],
    compatibles: ["M1"],
  },
];

function obtenerProducto(slug) {
  return productos.find((producto) => producto.slug === slug);
}

var articulos = [
  {
    slug: "que-es-una-codificadora-fechadora",
    titulo: "Codificadora fechadora: ¿qué es?",
    extracto: "Una solución manual, compacta e intuitiva para imprimir fechas, textos, códigos y más sobre diferentes superficies.",
    categoria: "Introducción",
    imagen: "/assets/blog/1/imagen-1.webp",
    imagenes: ["/assets/blog/1/imagen-2.webp"],
    secciones: [
      { parrafos: ["Una codificadora fechadora es una solución tecnológica manual, compacta e intuitiva que facilita el proceso de codificado e impresión de fechas, textos, códigos y más sobre diferentes superficies."] },
      { titulo: "Características", puntos: [
        { titulo: "Manual", texto: "Su diseño compacto y peso ligero permite imprimir con una sola mano, transportarla y utilizarla en cualquier lugar." },
        { titulo: "Táctil", texto: "La pantalla integrada trabaja con un software intuitivo para editar el contenido de forma fácil y rápida." },
        { titulo: "Impresión", texto: "Utiliza tinta solvente de secado rápido y larga duración sobre papel, plástico, cartón y otros materiales." },
        { titulo: "Durabilidad", texto: "Según el modelo, la batería recargable ofrece entre 4 y 16 horas de trabajo continuo." },
        { titulo: "Mantenimiento", texto: "Una carcasa resistente mantiene el equipo en óptimas condiciones con el cuidado adecuado." },
      ] },
      { titulo: "Cómo funciona", parrafos: ["La codificadora está diseñada para un uso rápido e intuitivo. Su boquilla integrada expulsa tinta solvente y su pantalla permite ingresar textos, fechas, logotipos y códigos QR o de barras con una experiencia similar a la de un teléfono celular."] },
    ],
  },
  {
    slug: "fecha-elaboracion-vencimiento-productos",
    titulo: "Fecha de elaboración y vencimiento en productos",
    extracto: "Por qué incluirlas, cómo se determinan y qué aportan a la seguridad del consumidor y al control del inventario.",
    categoria: "Buenas prácticas",
    imagen: "/assets/blog/2/imagen-1.webp",
    imagenes: ["/assets/blog/2/imagen-2.webp"],
    secciones: [
      { titulo: "¿Por qué incluirlas?", parrafos: ["Agregar la fecha de elaboración y caducidad es obligatorio en cada país para garantizar la seguridad del consumo del producto.", "La fecha de elaboración indica cuándo se fabricó un producto. La fecha de vencimiento marca el límite recomendado para consumirlo o utilizarlo."] },
      { titulo: "Proceso para establecerlas", parrafos: ["Para incluir fechas adecuadas se realizan pruebas de estabilidad bajo distintas condiciones. Los resultados permiten determinar cuánto tiempo mantiene el producto su calidad y pureza previstas, y definir una fecha segura para el consumidor."] },
      { titulo: "Importancia para tu negocio", parrafos: ["La impresión de estas fechas asegura calidad y seguridad, mejora el manejo del inventario y sirve como guía para una compra y un consumo responsables.", "En productos medicinales, de belleza o comestibles, la fecha correcta es importante tanto para el negocio como para el consumidor."] },
    ],
  },
  {
    slug: "beneficios-codificadora-fechadora-negocio",
    titulo: "Beneficios de incluir una codificadora fechadora",
    extracto: "Versatilidad, precisión y velocidad para producciones farmacéuticas, alimenticias, agrícolas y de empaquetado.",
    categoria: "Producción",
    imagen: "/assets/blog/3/imagen-1.webp",
    imagenes: ["/assets/blog/3/imagen-2.webp"],
    secciones: [
      { parrafos: ["Las codificadoras manuales están transformando el proceso de producción de distintas industrias. Brindan una solución tecnológica eficiente para imprimir sobre múltiples superficies y se adaptan a sectores como el farmacéutico, alimenticio, agrícola y de empaquetado."] },
      { titulo: "Usos principales", puntos: [
        { titulo: "Fechas y lotes", texto: "Imprime fechas de elaboración, caducidad y números de lote." },
        { titulo: "Etiquetado", texto: "Agrega códigos de barras o números de serie para mejorar el control del inventario." },
        { titulo: "Información comercial", texto: "Permite incluir información variable directamente sobre los productos." },
        { titulo: "Códigos QR", texto: "Facilita la trazabilidad o el acceso a información digital del negocio y del producto." },
      ] },
      { parrafos: ["El software permite controlar el texto que se desea imprimir. El bajo peso facilita el trabajo en diferentes áreas y varios modelos pueden operar de forma manual o automática junto con una banda transportadora."] },
    ],
  },
  {
    slug: "codificadora-ideal-para-tu-negocio",
    titulo: "¿Qué codificadora es ideal para tu negocio?",
    extracto: "Una guía para escoger el equipo según el tamaño de la empresa, la altura de impresión y el volumen de producción.",
    categoria: "Guía de compra",
    imagen: "/assets/blog/4/imagen-1.webp",
    imagenes: ["/assets/blog/4/imagen-2.webp", "/assets/blog/4/imagen-3.webp", "/assets/blog/4/imagen-4.webp"],
    secciones: [
      { parrafos: ["Nuestras codificadoras están diseñadas para empresas que necesitan incluir fechas, lotes, códigos e información adicional en sus productos. Su versatilidad permite adaptarlas a diferentes áreas de trabajo."] },
      { titulo: "Empresas pequeñas", puntos: [
        { titulo: "M1", texto: "Pantalla táctil, altura de 12,7 mm y longitud de hasta 1,5 m. Es compacta y permite imprimir varias líneas de texto." },
        { titulo: "B15", texto: "Trabaja mediante Wi-Fi, imprime hasta 12,7 mm de altura y es una buena opción para productos secos y congelados." },
      ] },
      { titulo: "Empresas medianas y grandes", puntos: [
        { titulo: "BT6205BL", texto: "Equipo tipo pistola, compacto y ligero, con batería de hasta 16 horas y uso manual o automático." },
        { titulo: "BT6210BL", texto: "Mayor altura de impresión, hasta 25,4 mm y diez líneas de contenido." },
        { titulo: "B45", texto: "Modelo industrial de dos tintas para imprimir hasta 50 mm y veinte líneas." },
        { titulo: "B85", texto: "Equipo de cuatro tintas para grandes alturas y hasta cuarenta líneas." },
      ] },
      { parrafos: ["Si aún no sabes qué codificadora se adapta a tu empresa, solicita una asesoría personalizada a <a href=\"mailto:ventas@rigelsa.com\">ventas@rigelsa.com</a>."] },
    ],
  },
  {
    slug: "extender-vida-tinta",
    titulo: "¿Cómo extender la vida de tu tinta?",
    extracto: "Limpieza, almacenamiento y cuidados sencillos para mantener una impresión definida por más tiempo.",
    categoria: "Mantenimiento",
    imagen: "/assets/productos/bb22b/principal.webp",
    video: "https://www.youtube-nocookie.com/embed/cbf6daTScR8",
    secciones: [
      { parrafos: ["Las codificadoras trabajan con tinta solvente de secado rápido. Un cuidado adecuado de la tinta extiende su vida útil y conserva la calidad de impresión."] },
      { titulo: "Limpieza", puntos: [
        { titulo: "Paso 1", texto: "Con la tinta bien cerrada, agítala de lado a lado durante 30 segundos." },
        { titulo: "Paso 2", texto: "Humedece ligeramente un paño de microfibra con alcohol, abre la tinta y limpia la boquilla de arriba hacia abajo cinco veces." },
      ] },
      { titulo: "Almacenamiento correcto", parrafos: ["Retira la tinta cuando no vayas a usar la codificadora durante más de diez minutos. Coloca el cobertor y guárdala en un área fresca y seca, lejos de temperaturas altas y humedad."] },
    ],
  },
  {
    slug: "agregar-textos-fechas-codigos",
    titulo: "¿Cómo agregar textos, fechas y códigos?",
    extracto: "Una explicación práctica para editar textos, logotipos, códigos de barras y códigos QR desde tu codificadora.",
    categoria: "Tutorial",
    imagen: "/assets/blog/6/imagen-1.webp",
    secciones: [
      { titulo: "Agregar fechas y textos", parrafos: ["Ingresa al apartado de edición y selecciona la opción de texto. Desde la vista previa puedes escribir una fecha o un texto, escoger fuente, tamaño, espaciado y propiedades como negrita, cursiva, subrayado o tachado."] },
      { titulo: "Agregar logotipos", parrafos: ["Guarda el logotipo en el pendrive en formato PNG o JPG. Conecta el USB, entra a Edición, selecciona Más e Imagen, y ajusta el archivo al tamaño deseado."] },
      { titulo: "Agregar un código de barras", parrafos: ["Dentro de Edición selecciona Código, ingresa la cadena que formará el código de barras y configura el tipo, la altura y la cifra antes de confirmar."] },
      { titulo: "Agregar un código QR", parrafos: ["Puedes escribir el enlace directamente en la opción QR o importar desde el pendrive un código creado previamente en formato PNG o JPG."] },
    ],
  },
  {
    slug: "por-que-escoger-tinta-bentsai",
    titulo: "¿Por qué escoger tinta BENTSAI?",
    extracto: "Calidad, rendimiento y adherencia para proteger la nitidez de cada impresión.",
    categoria: "Consumibles",
    imagen: "/assets/blog/7/imagen-1.webp",
    imagenes: ["/assets/blog/7/imagen-2.webp"],
    secciones: [
      { parrafos: ["Cuando la tinta termina, puedes buscar un consumible genérico o escoger tinta original BENTSAI. Ambas opciones pueden utilizar tinta solvente, pero la calidad de la tinta influye directamente en el resultado."] },
      { titulo: "Impresión clara y estable", parrafos: ["La tecnología de la tinta original ayuda a administrar el suministro en cada impresión y produce textos, códigos e imágenes nítidos sobre los productos."] },
      { titulo: "Tinta de secado rápido", parrafos: ["El solvente se adhiere con rapidez y reduce el riesgo de que la impresión se borre. Las tintas adecuadas pueden utilizarse incluso en productos destinados a congelación."] },
      { titulo: "Duración", parrafos: ["Aunque dos tintas tengan el mismo tamaño, la formulación, el sellado y la estabilidad de la boquilla pueden generar diferencias importantes en rendimiento y conservación."] },
    ],
  },
  {
    slug: "codificacion-secuencial",
    titulo: "Codificación secuencial",
    extracto: "Configura una base de datos para imprimir series variables de forma automática.",
    categoria: "Tutorial",
    imagen: "/assets/productos/bt6210bl/galeria-5.webp",
    secciones: [
      { parrafos: ["No es necesario editar manualmente una fecha o un número de lote después de cada impresión. La base de datos permite configurar una secuencia automática."] },
      { titulo: "Preparar el archivo", parrafos: ["Crea la base de datos en Excel sin dejar celdas vacías entre los registros y guarda el archivo en formato CSV UTF-8."] },
      { titulo: "Cargar la secuencia", parrafos: ["Copia el CSV en la carpeta de base de datos del pendrive. En la codificadora entra a Edición, Más y Almacén para seleccionar el archivo."] },
      { titulo: "Elegir el formato", parrafos: ["Antes de imprimir, define si el contenido se utilizará como texto variable, código QR o código de barras. Confirma la vista previa y el número de inicio de la secuencia."] },
    ],
  },
  {
    slug: "codificacion-automatica",
    titulo: "Codificación automática",
    extracto: "Integra una codificadora compatible a una banda transportadora y agiliza tu línea de producción.",
    categoria: "Automatización",
    imagen: "/assets/productos/bt6205bl/galeria-5.webp",
    secciones: [
      { parrafos: ["La línea BT combina un diseño ligero con un software sencillo y puede adaptarse al trabajo manual o automático."] },
      { titulo: "Ventajas", puntos: [
        { titulo: "Mayor velocidad", texto: "La banda transportadora aumenta la cantidad de impresiones y reduce el margen de error." },
        { titulo: "Datos variables", texto: "Una base de datos permite trabajar con codificación secuencial y revisar la información antes de imprimir." },
        { titulo: "Continuidad", texto: "La automatización disminuye interrupciones y mantiene el ritmo de producción." },
      ] },
      { titulo: "Configuración", parrafos: ["En Ajustes selecciona Impresión y cambia el modo a Inducción. Configura el retraso según el área y la distancia de impresión. Después conecta la codificadora a la banda transportadora y al sensor, dirige el sensor hacia los productos e inicia la impresión."] },
      { parrafos: ["Para una capacitación sobre la instalación de la banda transportadora, contacta a <a href=\"mailto:ventas@rigelsa.com\">ventas@rigelsa.com</a> o por WhatsApp al +593 93 947 4695."] },
    ],
  },
];

function obtenerArticulo(slug) {
  return articulos.find((articulo) => articulo.slug === slug);
}

window.RIGEL_DATA = { productos: productos, articulos: articulos };
}());

